version: '3'
services:
  movies:
    image: venkatesh06119/paytmmovies:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3

  train:
    image: venkatesh06119/paytmtrain:latest

    ports:
      - "85:80"
    deploy:
      replicas: 3

  dth:
    image: venkatesh06119/paytmdth:latest

    ports:
      - "86:80"
    deploy:
      replicas: 3

  rec:
    image: venkatesh06119/paytmrec:latest

    ports:
      - "87:80"
    deploy:
      replicas: 3
